### ISSUE TITLE
Official firmware source ?

### ISSUE THREAD

**Issue by G-Ray** [vulgo/kingston-a2000-firmware-bin-linux#1]
Thanks for this helpful repository.

The old firmware could be downloaded from kingston's website ([https://media.kingston.com/support/downloads/S5Z42105.zip]()).
However, the new firmware is not accessible from it, https://media.kingston.com/support/downloads/S5Z42109.zip returns a 404.

Is there an official source from where the new release "S5Z42109" can be found ?

**Comment by vulgo** [comment]
I heard that Kingston technical support are distributing it directly to users, you can contact them via their website.

**Comment by vulgo** [comment]
Added note and link to Kingston contact form to the repository readme.
