### ISSUE TITLE
The firmware image specified for activation is invalid

### ISSUE THREAD

**Issue by hyperbart** [vulgo/kingston-a2000-firmware-bin-linux#3]
Ubuntu 22.04.1 LTS

Had a problem last night with the SSD acting up, found this GitHub via a forum thread.

Tried to update the firmware, but was unsuccessful, see errors below:

```
root@nas:~/A2000_FW_Update# md5sum -c S5Z42109.md5
S5Z42109.bin: OK
root@nas:~/A2000_FW_Update# nvme fw-download /dev/nvme0n1 --fw=S5Z42109.bin
Firmware download success
root@nas:~/A2000_FW_Update# nvme fw-activate /dev/nvme0n1 --slot=1 --action=1
NVMe status: FIRMWARE_IMAGE: The firmware image specified for activation is invalid and not loaded by the controller(0x107)
Multiple Update Detected (MUD) Value: 46
Detected an overlapping firmware/boot partition image update command sequence due to processing a command from an Admin SQ on a controller
```

**Comment by vulgo** [comment]
Hi, I'm in the dark here, better to search the issues or open a new one at [github.com/linux-nvme/nvme-cli](https://github.com/linux-nvme/nvme-cli) regarding this error message as it is part of nvme.c. Sorry I'm not more help. Thanks.
